<a href="https://colab.research.google.com/github/kaushikykk/scaler/blob/main/python_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import auth
auth.authenticate_user()
!git clone https://github.com/kaushikykk/scaler.git

fatal: destination path 'scaler' already exists and is not an empty directory.


In [ ]:
 w = int(input("please enter the amount to be withdrawn - Rs. "))
if (w < 200):
  print( "it should be 200 or more")
elif (w > 200 and w < 500):
  print("your number is between 200 and 500, please pick multiples of 2 and 5")
elif (w%5 == 0):
  print("available")
else:
  print("enter amount in multiples 500 or 200")

please enter the amount to be withdrawn - Rs. 1800
available


In [ ]:
A = int(input("Please give number for angle A "))
B = int(input("Please give number for angle B "))
C = int(input("Please give number for angle C "))

z = A+B+C
if(z == 0):
  print("All angles are zero")
elif (z < 180):
  print("Less than 180 for  a triangle")
elif(z > 180):
  print("more than 180 for a triangle")
else:
  print("Its a triangle")



Please give number for angle A 60
Please give number for angle B 60
Please give number for angle C 60
Its a triangle


In [ ]:
a1 = int(input())
a2 = int(input())
b1 = int(input())
b2 = int(input())

avg_A = (a1 + a1)/2
avg_B = (b1 + b2)/2

if avg_A > avg_B:
    print ("True")
else:
    print("False")



54
99
77
90
False


In [ ]:
import numpy as np
a = [5,7,0.5]

a = np.array([5,7,0.5])

In [ ]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
(x <= 15)
print(x)

[-5  9 20 25 -3  5 16 10 -8]


In [ ]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) ]
print(x)

[-5  9 20 25 -3  5 16 10 -8]


In [ ]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5)  & (x <= 15)] *= -1
print(x)

In [ ]:
x = 1
n = int(input())
while x<=n:
  print(x)
  x += 2

10
1
3
5
7
9


In [ ]:
s = int(input())
e = int(input())
count = s
x = []

while s <= e:
  if s % 2 == 0:
    print(s, "is even")

  s +=1





7
8
8 is even


In [ ]:
import numpy as np

m1 = np.array([[1,2,3],[3,4,5]])

m1.shape
m1.ndim


2

In [ ]:
m2 = np.arange(2,6)
m2.ndim
m2.flatten()


array([2, 3, 4, 5])

In [ ]:
# Indexing 2D list

In [ ]:
m3 = np.arange(1, 12)
m3[(2,6)]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
import numpy as np
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
print(a)
print(a.transpose()[-2,-2])

[[34 28 55]
 [ 8 56  3]
 [77 87 19]]
56


In [ ]:
v = np.array([200,300,400])
v[:,None]

array([[200],
       [300],
       [400]])

In [ ]:
# Nested loops:

TC = int(input())
for i in range(TC):
    N = int(input())
    reversed_num = 0
    while N > 0:
        reversed_num = (reversed_num * 10) + (N % 10)
        N = N // 10
    print(reversed_num)

In [ ]:
N_size = int(input())  # Number of test cases

for i in range(N_size):
    N_lines = int(input())  # Number of integers in this test case

    # Take the list of integers as input
    shift = list(map(int, input().split()))

    # Validate that the length matches N_lines
    if len(shift) != N_lines:
        print("Error: Input length does not match N_lines.")
        continue

    # Right rotate the list by 1
    shift = [shift[-1]] + shift[:-1]

    # Print the rotated list
    print(shift)


1
5
1 2 3 4 5 
[5, 1, 2, 3, 4]


In [ ]:
N = int(input())
new_arr = []
for i in range(1,N,-1):
  arr = int(input())
  new_arr.append(i)
    # final = new_arr[:-1]
  print(new_arr, end=" ")

5


In [ ]:
word = "Scaler Data Science Course"
word_list = list(word)
for i in word_list:
  print(i.index, end=" ")
print(i)
print()

<built-in method index of str object at 0x79685d3959f0> <built-in method index of str object at 0x79685d35d8b0> <built-in method index of str object at 0x79685d38bf30> <built-in method index of str object at 0x79685d3b1870> <built-in method index of str object at 0x79685d39d630> <built-in method index of str object at 0x79685d577ef0> <built-in method index of str object at 0x79685d39c130> <built-in method index of str object at 0x79685d3b0f30> <built-in method index of str object at 0x79685d38bf30> <built-in method index of str object at 0x79685d35d1b0> <built-in method index of str object at 0x79685d38bf30> <built-in method index of str object at 0x79685d39c130> <built-in method index of str object at 0x79685d3959f0> <built-in method index of str object at 0x79685d35d8b0> <built-in method index of str object at 0x79685d5751b0> <built-in method index of str object at 0x79685d39d630> <built-in method index of str object at 0x79685d3b05f0> <built-in method index of str object at 0x79685d

In [ ]:
word = "Scaler Data Science Course"

# Split and reverse
reversed_words = word.split()
print(" ".join(reversed_words))


Scaler Data Science Course


In [ ]:
# Original string
word = "Scaler Data Science Course"

# Split the string into a list of words
word_list = word.split()

# Iterate over the list with indexes
for index, w in enumerate(word_list):
    print(f"Index: {index}, Word: {w}")


Index: 0, Word: Scaler
Index: 1, Word: Data
Index: 2, Word: Science
Index: 3, Word: Course


In [ ]:
arr1 = [1,2,3]
arr2 = [6,5,4]

arr1.sort()
print(arr1)

# arr1.append(arr2)
# print(arr1)

# arr1.extend(arr2)
# print(arr1)



[1, 2, 3]


In [ ]:
a = 5

In [ ]:
b = 10
a = b
b = a

In [ ]:
print(a)
print(b)

10
10


In [ ]:
class Circle:
    pi = 3.14
    def __init__(self, diameter):
        self.radius = diameter / 2

    def circumference(self):
        return 2 * self.pi * self.radius


pizza = Circle(12)
print(pizza.circumference())

pizza = Circle(6)
print(pizza.circumference())

pizza = Circle(12)
print(pizza.self.circumference())

pizza = Circle(6)
print(pizza.self.circumference())

37.68
18.84


AttributeError: 'Circle' object has no attribute 'self'

In [ ]:
import pandas as pd

data = {
    'name': ['Jim', 'Clarke', 'Kent', 'Mark'],
    'username': ['itsjimhere', 'clark002', 'itskentment', 'markyoumustknow'],
    'userid': [20, 10, 86, 21]
}

df = pd.DataFrame(data)
df

name         username  userid
0     Jim       itsjimhere      20
1  Clarke         clark002      10
2    Kent      itskentment      86
3    Mark  markyoumustknow      21

In [ ]:
def check(name,username):
    return name.lower() in username

df[~(df.apply(lambda x:check(x['name'],x['username']), axis=1))]['userid']

1    10
Name: userid, dtype: int64

In [ ]:
import pandas as pd

data = {
    'roll_no': [1, 2, 1, 3, 1, 3, 3, 3, 2, 2, 1, 2],
    'subject': ['NN', 'DL', 'ML', 'Prob', 'DL', 'ML', 'DL', 'NN', 'NN', 'Prob', 'Prob', 'ML'],
    'marks': [97, 63, 63, 71, 64, 90, 66, 46, 74, 62, 94, 67]
}

df = pd.DataFrame(data)
max_marks = list(df.groupby('subject'))
max_marks


[('DL',
     roll_no subject  marks
  1        2      DL     63
  4        1      DL     64
  6        3      DL     66),
 ('ML',
      roll_no subject  marks
  2         1      ML     63
  5         3      ML     90
  11        2      ML     67),
 ('NN',
     roll_no subject  marks
  0        1      NN     97
  7        3      NN     46
  8        2      NN     74),
 ('Prob',
      roll_no subject  marks
  3         3    Prob     71
  9         2    Prob     62
  10        1    Prob     94)]

In [ ]:
import pandas as pd

data = {
    'roll_no': [1, 2, 1, 3, 1, 3, 3, 3, 2, 2, 1, 2],
    'subject': ['NN', 'DL', 'ML', 'Prob', 'DL', 'ML', 'DL', 'NN', 'NN', 'Prob', 'Prob', 'ML'],
    'marks': [97, 63, 63, 71, 64, 90, 66, 46, 74, 62, 94, 67]
}

df = pd.DataFrame(data)
df

max_marks = df.groupby('subject').max()
max_marks



roll_no  marks
subject                
DL             3     66
ML             3     90
NN             3     97
Prob           3     94

In [ ]:
class Student:
    def __init__(self, marks1, marks2, credits1, credits2):
        self.marks = [marks1, marks2]
        self.credits = [credits1, credits2]

    def grade_point_average(self):
        # Grade point calculation based on marks
        def get_grade_point(marks):
            if marks >= 90:
                return 10
            elif marks >= 75:
                return 9
            elif marks >= 60:
                return 8
            elif marks >= 45:
                return 7
            else:
                return 0

        # Handle the special case where both credits are 0
        total_credits = sum(self.credits)
        if total_credits == 0:
            return -1.0

        # Calculate total weighted points
        total_weighted_points = sum(get_grade_point(mark) * credit for mark, credit in zip(self.marks, self.credits))

        # Calculate GPA and round to two decimal places
        gpa = total_weighted_points / total_credits
        return round(gpa, 2)
s1 = Student(5, 6, 0, 0)

# Call the grade_point_average method
output1 = s1.grade_point_average()

# Print the GPA as an integer
print(int(output1))


-1


In [ ]:
class BankAccount:

  def __init__(self, acc_no, amount):
    self.acc_no = acc_no
    self.amount = amount


  def CheckBalance(self):
    print(f"{self.acc_no} \t {self.amount}")

ac1 = BankAccount(100, 1000)
ac1.CheckBalance()

100 	 1000


In [ ]:
#when ever we need instance variable inside the class "SELF" is needed

class A:
  print("Am I a Class")

# A()
# obj1 = A()
if A():
  print(A())



Am I a Class


In [ ]:

class A:
 def __init__(self, a):
  self.a = a
 def __add__(self, b):
  if isinstance(b, int):
    return A(self.a + b)
  return A(self.a + b.a)
 def __str__(self):
    return f"{self.a}"

one = A(1)
two = A(2)


print(one + two + 100)


103


In [ ]:
class A:
  def __init__(self, a):
    self.a = a
  def __add__(self, b):
    if isinstance(b, int):
      return A(self.a + b) # ins3 + int
    return A(self.a + b.a) # ins3 = ins1 + ins2
  def __str__(self):
    return f"{self.a}"

one = A(1)
two = A(2)

# ins1 + ins2 + int
print(one + two + 100)

103


In [ ]:
class A:

 def __init__(self, a):
  self.a = a
 def __add__(self, b):
  if isinstance(b, int):
    return A(self.a + b)
  return A(self.a + b.a)
 def __str__(self):
    return f"{self.a}"

one = A(1)
two = A(2)


print(one + two + 100)

103


In [ ]:
class A:
  print("Am I a Class")

A()

Am I a Class


In [ ]:
class BankAccount:

  def __init__(self, acc_no, amount):
    self.acc_no = acc_no
    self.amount = amount

  def __add__(self, other):
    return self.acc_no + other.acc_no
  def CheckBalance(self):
    print(f"{self.acc_no} \t {self.amount}")

ac1 = BankAccount(100, 1000)
ac2 = BankAccount(101, 100)
ac1 + ac2

201

In [ ]:
class Student():

    def __init__(self, marks1,marks2,credits1, credits2):
        #YOUR CODE GOES HERE
        self.marks = [marks1, marks2]
        self.credits = [credits1, credits2]

    def grade_point_average(self):
        gpa=0
        points = []
        cs = []
        for mark in self.marks:
            if mark > 90:
                points.append(10)
            elif mark > 75:
                points.append(9)
            elif mark > 60:
                points.append(8)
            elif mark > 45:
                points.append(7)
            else:
                points.append(0)

        # print(points)
        # print(self.credits)

        for i in range(len(points)):
          cs.append(points[i] * self.credits[i])

        # print(cs)
        css = sum(cs)
        # print(css)
        # print(sum(self.credits))


        gpa = css/sum(self.credits)
        # print(gpa)
        return gpa




st1 = Student(85, 76, 3, 4)
st1.grade_point_average()

9.0

In [ ]:
class Parent:
  def __init__(self):
    pass
  def print(self):
    print("60")

class Child(Parent):
  # def __init__(self):
  #   super().__init__()
  # def type(self):
  #   self.print()
  def __init__(self):
    super().__init__()
  def type(self):
    super().print()



C=Child()
C.type()

60


In [ ]:
class A:
   def one(self):
       return self.two()
   def two(self):
       return 'A'
class B(A):
   def two(self):
       return 'B'
obj= B()
print(obj.one())

In [ ]:
class A:
   def one(self):
       return self.two()
   def two(self):
       return 'A'
class B(A):
   def two(self):
       return 'B'
obj= B()
print(obj.one())

B


In [ ]:
class A:
  __a = 100
  def test(self):
    return self.__a

obj = A()
obj.test())






SyntaxError: unmatched ')' (<ipython-input-21-119928ddbd6c>, line 7)

In [ ]:
lst = [2,4,5,9]

In [ ]:
square = [x**2 for x in lst]
print(square)

[4, 16, 25, 81]


In [ ]:
lst = [2,3,4,5,6,7,8,9,10]


def square(x):
  square = []
  for i in range(len(x)):
    result = x[i]**2
    square.append(result)
  return square

square(lst)
    i += 1

square(lst)


IndentationError: unexpected indent (<ipython-input-16-2343b4b898be>, line 12)

In [ ]:
n =int(input())
for i in range(n):
    print("*")
    for j in range(n):
        print("** " )
        for j in range(n):
          print("*** " )
          for j in range(n):
            print("**** ")
            for j in range(n):
                print("***** ")
                break
            break
          break
        break

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git


In [ ]:
n = int(input())
for i in range(n):
   n
  print("n*i+1" )

5
n*i+1
n*i+1
n*i+1
n*i+1
n*i+1


In [ ]:
n = int(input())
for i in range(n):
  for j in range(-i,1):
    print("*",end = " ")
  print()


20
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 
* * * * * * * * 
* * * * * * * * * 
* * * * * * * * * * 
* * * * * * * * * * * 
* * * * * * * * * * * * 
* * * * * * * * * * * * * 
* * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * 


In [ ]:
T = int(input()) ### Number of test case
for i in range(T):
  N = int(input())
  N = []
  result = reversed(N)
return result


1
103


SyntaxError: 'return' outside function (<ipython-input-87-b256571d3371>, line 6)

In [ ]:
def solve_test_cases():
    T = int(input())  # Number of test cases
    results = []
    for i in range(T):
        N = int(input())
    # This will be an empty list, is that intended?
        results.append(N)
        print(results) # Store the result
        reverse = results[-1::]
    return reverse

In [ ]:
print(solve_test_cases())

1
12345
[12345]
[12345]


In [ ]:
def solve_test_cases():
    T = int(input())  # Number of test cases
    results = []

    for _ in range(T):
        N = int(input())  # Read integer input
        results.append(N)  # Store the result

    return results[::-1]  # Return the reversed list


In [ ]:
print(solve_test_cases())


1
12345
[12345]


In [ ]:
def solve_test_cases():
    T = int(input("Enter number of test cases: "))  # Read number of test cases
    results = []

    for _ in range(T):
        N = int(input("Enter a number: "))  # Read integer input
        results.append(N)  # Store the result

    return results[::-1]  # Return the reversed list

# Running the function and printing output
print(solve_test_cases())


Enter number of test cases: 1
Enter a number: 123456
[123456]


In [ ]:
def solve_test_cases():
    T = int(input("Enter number of test cases: "))  # Number of test cases
    results = []

    for _ in range(T):
        N = int(input("Enter a number: "))  # Read integer input
        reversed_number = int(str(N)[::-1])  # Reverse the digits
        results.append(reversed_number)  # Store the reversed number

    return results

print(solve_test_cases())  # Ensure the output is displayed


Enter number of test cases: 1
Enter a number: 12345
[54321]


In [ ]:
T = int(input())
x = []
for i in range(T):
    N = int(input())
    for j in range(N):
        x.append(j)
        y = reversed(x)
    print(y)

1
1234


In [ ]:
T = int(input())  # Number of test cases

for i in range(T):
    A = int(input())  # First number
    B = int(input())  # Second number
    min_num = min(A, B)

    while True:
        if min_num % A == 0 and min_num % B == 0:
            print(min_num)  # Found LCM
            break
        min_num += 1  # Try the next multiple


1
6
8
24


In [ ]:
A = int(input())
for i in range(A):
    x = x[::-1]
    print(x)

1
[100, 98, 96, 94, 92, 90, 88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66, 64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, 100, 100, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [ ]:
a=int(input())
rev=str(a)
if rev==rev[-1::-1]:
    print("Yes")
else:
    print("No")

121
Yes


In [ ]:
N = int(input())
for i in range(N):
    print(i, end= " ")
    for j in (i,1):
        print(j, end = " ")

3
0 0 1 1 1 1 2 2 1 

In [ ]:
n = int(input())
for i in range(1,n):
  for j in range(n-1,1,-1):
    print(j,end = " ")
  print()

5
4 3 2 
4 3 2 
4 3 2 
4 3 2 


In [ ]:
import numpy as np
arr = np.arr[131, 150, 140, 142, 152]
arr

AttributeError: module 'numpy' has no attribute 'arr'